### ISSUE TITLE
Site Title and Tagline

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/RokoPhoto#16]
The tagline is not showing, when no logo is set up, only the site title

**Comment by HardeepAsrani** [comment]
@rodica-andronache I talked about this with @ineagu when I was working on it and we decided to go with only the title because tagline was looking ugly at this spot. Apart from that, the tag line also appears on the blog header.

And it's not required by WordPress theme guidelines. What say? :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani it's fine for me :) we just need to remove it from the documentation

**Comment by HardeepAsrani** [comment]
@rodica-andronache Remove from theme? I don't get it.

I need to check Github activity more. :p

**Comment by rodica-andronache** [comment]
@HardeepAsrani I mean to remove the possibility to change the tagline in customizer , since we do not use it in the theme. Like this http://speakinginbytes.com/2012/11/removing-the-tagline-from-the-theme-customizer-in-wordpress/. And to remove it from documentation also :D

**Comment by ineagu** [comment]
I am not sure is a great idea, the tagline for example is a generic wp
thing, it's used in the site title/ description and other plugins can use
it no ?

On Mon, Mar 30, 2015 at 2:05 PM, rodica-andronache <notifications@github.com

**Comment by HardeepAsrani** [comment]
Yes. Even blog pages uses site title and tagline so it's not a great idea
to remove it. :)

**Comment by rodica-andronache** [comment]
ok, I understand :)

**Comment by HardeepAsrani** [comment]
Yea. Not just that but the theme also uses these values in other places,
such as blog page template.

On Monday, March 30, 2015, Ionut Neagu <notifications@github.com> wrote:

> I am not sure is a great idea, the tagline for example is a generic wp
> thing, it's used in the site title/ description and other plugins can use
> it no ?
>
> On Mon, Mar 30, 2015 at 2:05 PM, rodica-andronache <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > wrote:
>
> > @HardeepAsrani <https://github.com/HardeepAsrani> I mean to remove the
> > possibility to change the tagline in customizer , since we do not use it
> in
> > the theme. Like this
> >
> http://speakinginbytes.com/2012/11/removing-the-tagline-from-the-theme-customizer-in-wordpress/
> .
> > And to remove it from documentation also :D
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Codeinwp/RokoPhoto/issues/16#issuecomment-87651613>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/RokoPhoto/issues/16#issuecomment-87725766>.
>


-- 
Regards,
Hardeep Asrani
