### ISSUE TITLE
License Code

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/RokoPhoto#18]
The license code system has not been added to this theme. @ineagu @rodica-andronache

**Comment by ineagu** [comment]
Can you please let mariusC know about it?

**Comment by HardeepAsrani** [comment]
@selu91 We need you here. :D

**Comment by selu91** [comment]
@HardeepAsrani in order to solve the license problem for users who dont see the license you need to go on their payment details and click on generate license. After this you will see the license for the missing products.

**Comment by HardeepAsrani** [comment]
@selu91 I don't have access to the dashboard. Which general settings are you talking about? :)
