### ISSUE TITLE
Dropdown menu not working

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/RokoPhoto#2]

**Comment by HardeepAsrani** [comment]
The original HTML theme didn't had it either.

**Comment by ineagu** [comment]
@HardeepAsrani ok, but we still to do it :D, do you wanna do it?

**Comment by HardeepAsrani** [comment]
I never had luck with drop down menus... :p

**Comment by ineagu** [comment]
@claudiuvertistudio please take a look at this next week.

**Comment by ineagu** [comment]
Basically I hope we can get this published on wednesday ( fix, test everything and create the page on the live site )
