### ISSUE TITLE
Portfolio items

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/RokoPhoto#4]
@HardeepAsrani I can't figure out how to display all the portfolios. It shows everyone except for one item, the last added. Can you please check if this happens for you too?

**Comment by HardeepAsrani** [comment]
How many items you had? @rodica-andronache

**Comment by ineagu** [comment]
@rodica-andronache also portfolio items should open in a lightbox on click ( like the wrapbootstrap demo ), not on a new page. 

The menu on demo should also scroll using # not open new pages.

**Comment by rodica-andronache** [comment]
@HardeepAsrani this happens for any number of portfolios. @ineagu ok, I will do that too

**Comment by HardeepAsrani** [comment]
@rodica-andronache I've fixed this issue in https://github.com/Codeinwp/RokoPhoto/commit/ca61b3425809faa42ac53fb1df6fbeb7bf5e9e6b so please check it out if you're still facing it. :)

Working for me.

**Comment by rodica-andronache** [comment]
@HardeepAsrani yes, it's working now :) Could you please give me the HTML for the theme? I can't find it. Or do you want to do the part which opens the portfolios in a lightbox?

**Comment by HardeepAsrani** [comment]
I'll do that too. You can assign this to me. :) @rodica-andronache

**Comment by ineagu** [comment]
@HardeepAsrani Also portfolio items should open in a lightbox on click ( like the wrapbootstrap demo ), not on a new page.

The menu on demo should also scroll using # not open new pages.

**Comment by HardeepAsrani** [comment]
@ineagu 

This commit fixed the scroll issue: https://github.com/Codeinwp/RokoPhoto/commit/d250f86576e3cc91e2f8257af534a180746bc08a

**Comment by HardeepAsrani** [comment]
@ineagu And for portfolio, there are two styles of lightboxes/modal, which one do you want? 

Lightbox: http://jennylynpereira.com/demo/html/awesome-photography2/index2.html
Modal: http://jennylynpereira.com/demo/html/awesome-photography2/index.html

:)

**Comment by HardeepAsrani** [comment]
Only the modal one can show the content, while Lightbox one only shows the image.

**Comment by ineagu** [comment]
I would like index.html with content also

**Comment by HardeepAsrani** [comment]
@ineagu @rodica-andronache Modal added to portfolio in https://github.com/Codeinwp/RokoPhoto/commit/ef47155eac49eccb5895dc21cf00120da7ffee27.

I've added Modal + Smooth Scroll, so shall we wrap this ticket up? And don't forget to test both of them. :)
